### ISSUE TITLE
C# documentation is out of date

### ISSUE THREAD

**Issue by spektro37** [spvessel/spacevil#5]
I have found that documentation located at https://spvessel.com/spacevil/docs/csharp/html/class_space_v_i_l_1_1_core_window.html seems to be out of date. At least it doesn't mention CoreWindow.ToggleFullScreen() anywhere.

**Comment by spvessel** [comment]
Yeah, the documentation is do out of date. Sorry. We are working on it. I will notice you here when it is done.
PS. I understand that this can be inconvenient, but if you have questions, I will be happy to answer you. I will try to update the documentation as soon as possible.

**Comment by spvessel** [comment]
I tried to show how to do a most things in examples that are provided by this repository, but of course that examples (demo apps, tutorials, simple examples) does not cover all frameworks features.

**Comment by spektro37** [comment]
Thank you for your quick response and agreeing to answer questions I might have.

I have to admit that I didn't look through all the examples you have provided, so maybe answers to some of my questions are already there, but it requires significant amount time to analyse and digest these examples and flesh out examples of using separate elements and their properties. For example, I know exactly what I want to build and I am interested in how I can position a Label element in the main window or do certain things with other elements. Using SetX() and SetY() did not have the expected effect and then I had to go into some of the examples looking for any information about positioning elements.

I have read your [article][1] on Habr and I agree that having a fully working application as an example is good for understanding how the framework works in the real world. However, I feel that [documentation][2] also needs to have comprehensive description of the element, it's properties, public methods (not only list them, though I admit that their names are very descriptive) and a couple of examples of how it can be used with only necessary context. Having this would make the learning curve less steep.

I don't want to look to picky, sorry if this is the case. :) At the moment I can say that I like SpaceVIL and I simply want it to be easier to learn and use.

If I will have questions, should I ask them by creating a separate issue per question here?

[1]:https://habr.com/ru/post/448790/
[2]:https://spvessel.com/spacevil/docs/csharp/html/annotated.html

**Comment by spvessel** [comment]
Yes, I agree that need a solid documentation for framework. 
And about your question of positioning elements... hmmm... Using SetX () and SetY () will definitely not give the expected effect because of SpaceVIL markup system and default Label style. 
Common markup system works with the following properties:
1. SizePolicy (Fixed, Expand)
2. ItemAlignment (Left, Right, Top, Bottom, HCenter, VCenter)
3. Container Padding
4. Item Margin 
5. Item Size (size, max size, min size)
In that markup system, methods like SetX(), SetY() do not work (work only in FreeArea, IFloatingItem and any others that implement IFreeLayout or IHLayout, IVLayout).
And if you even set a desired ItemAlignment properties you still see that the Label stays in the same place. It because of default Label style that has SizePolicy property is set to Expand.

Examples:
```
public class MyWindow : ActiveWindow
{
    // implement ActiveWindow class
    public override void InitWindow()
    {
        // window parameters
        SetParameters("MyWindow", "MyWindow", 300, 300);
        Label label = new Label("Hello World!");
        label.SetAlignment(ItemAlignment.Bottom, ItemAlignment.Right);
        AddItem(label);
    }
}
```
You get the result:
![image](https://user-images.githubusercontent.com/45689928/74084016-7e61e880-4a7b-11ea-852d-a0b636fb0bcc.png)
That happens because of Label SizePolicy property by default is set to Expand. To make sure we can change the background color of label:
```
public class MyWindow : ActiveWindow
{
    // implement ActiveWindow class
    public override void InitWindow()
    {
        // window parameters
        SetParameters("MyWindow", "MyWindow", 300, 300);
        Label label = new Label("Hello World!");
        label.SetAlignment(ItemAlignment.Bottom, ItemAlignment.Right);
        label.SetBackground(Color.Chocolate); // bg color
        AddItem(label);
    }
}
```
Result:
![image](https://user-images.githubusercontent.com/45689928/74084125-c59ca900-4a7c-11ea-8b6d-547bf6bd00a6.png)

But we can change SizePolicy property to Fixed:
```
public class MyWindow : ActiveWindow
{
    // implement ActiveWindow class
    public override void InitWindow()
    {
        // window parameters
        SetParameters("MyWindow", "MyWindow", 300, 300);
        Label label = new Label("Hello World!");
        label.SetAlignment(ItemAlignment.Bottom, ItemAlignment.Right);
        label.SetBackground(Color.Chocolate); // bg color

        // change SizePolicy
        label.SetSizePolicy(SizePolicy.Fixed, SizePolicy.Fixed);
        label.SetSize(label.GetTextWidth() + 30, 60);

        AddItem(label);
    }
}
```

Result:
![image](https://user-images.githubusercontent.com/45689928/74084166-64c1a080-4a7d-11ea-97bd-f6cb91cbd15a.png)

And the last thing (optionally). Label can change position of text via method SetTextAlignment():
```
public class MyWindow : ActiveWindow
{
    // implement ActiveWindow class
    public override void InitWindow()
    {
        // window parameters
        SetParameters("MyWindow", "MyWindow", 300, 300);
        Label label = new Label("Hello World!");
        label.SetAlignment(ItemAlignment.Bottom, ItemAlignment.Right);
        label.SetBackground(Color.Chocolate); // bg color

        // change SizePolicy
        label.SetSizePolicy(SizePolicy.Fixed, SizePolicy.Fixed);
        label.SetSize(label.GetTextWidth() + 30, 60);

        // change text alignment
        label.SetTextAlignment(ItemAlignment.Bottom, ItemAlignment.Right);

        AddItem(label);
    }
}
```

Result:
![image](https://user-images.githubusercontent.com/45689928/74084198-def22500-4a7d-11ea-949a-4c0594afa709.png)

So what are the conclusions?
1. Common markup system is very useful.
2. I really need to provide all the default styles of items via some sort of documentation...

Thanks for letting me know about my mistakes!

**Comment by spektro37** [comment]
Thank you very much for the detailed answer! The picture is becoming more clear now. :)
